In [ ]:
# 1
a = int(0.2467 * 12 + 4.159)
print(a)


# 2
b = 48584 * 36
print(b)


# 3 a#b&c%d로 변경하여 출력해 보자.
s = "a@b@c@d"

v1 = s.index("a") + 1
v2 = s.index("b") + 1
v3 = s.index("c") + 1

s = list(s)
s[v1] = "#"
s[v2] = "&"
s[v3] = "%"
print("".join(s))


# 4 btc와 krw로 나눠보세요.
ticker = "btc_krw"
ticker = ticker.split("_")
print(ticker)


# 5 연도, 월, 일로 나눠보세요.
date = "2020-12-30"
date = date.split("-")
print(date[:])


# 6 오른쪽에 공백이 있을 때 이를 제거해보세요.
data = "039490     "
data = data.rstrip()
print(data)


# 7 % formatting을 사용해서 다음과 같이 출력해보세요.
# 이름: 김민수 나이: 10
# 이름: 이철희 나이: 13
name1 = "김민수"
age1 = 10
name2 = "이철희"
age2 = 13
print("이름: %s 나이: %d\n이름: %s 나이: %d" % (name1, age1, name2, age2))


# 8 format( ) 메서드를 사용해서 7번 문제를 다시 풀어보세요.
print("이름: {name1} 나이: {age1}\n이름: {name2} 나이: {age2}".format(name1="김민수", age1=10, name2="이철희", age2=13))


# 9 컴마를 제거한 후 이를 정수 타입으로 변환해보세요.
price = "5,969,782,550"
price = price.replace(",", "")
print(price)


# 10 '2020/12'만 출력하세요.
s = "2020/12(E) (IFRS연결)"
# print(s[0:7])

v = s.index("(E)")
s = list(s)
del s[v:]
print("".join(s))


# 11 소문자 'a'를 대문자 'A'로 변경하세요.
string = 'abcdfe2a354a32a'
str2 = string.replace("a", "A")
print(str2)


# 12 주민등록번호에서 성별을 나타내는 숫자를 출력해 보세요.
pin = "881120-1068234"
s_id = pin.index("-") + 1
person_s = pin[s_id]
print(person_s)


# 13 리스트를 Life is too short 문자열로 만들어 출력해 보세요.(join 활용)
L = ['Life', 'is', 'too', 'short']
print(" ".join(L))


# 14 리스트에 대해 데이터 참조하는 연습을 해보세요.
a = [1, 2, 3, ['a', 'b', 'c'], 4, 5]
data1 = a[3]
data2 = a[3][1]
data3 = a[3][:]
data4 = a[3][1:]
data5 = a[3][2:]

print("{data1}\n{data2}\n{data3}\n{data4}\n{data5}".format(data1=data1, data2=data2, data3=data3, data4=data4, data5=data5))