In [87]:
import pandas as pd

# *titanic 데이터셋에 대해 다음 작업을 수행하시오.
df = pd.read_csv("../../개인 필기/data/datasets/titanic/train.csv")
df

# 1. 승선항구가 'C'인 자료만 추출하시오.
df[df.Embarked == 'C']

# 2. SibSp + Parch 의 합이 0인 자료만 추출하시오.
df[df.SibSp + df.Parch == 0]

# 3. Pclass가 1인 자료만 추출하시오.
df[df.Pclass == 1]

# 4. Fare 열 값이 20이상 50미만인 자료만 추출하시오.
df[(df.Fare >= 20) & (df.Fare < 50)]


# * yahoo finance 사이트 데이터셋(finance.yahoo.com)

# 5. 2024년도 삼성전자 주가데이터를 가져온 다음 아래와 같은 작업을 수행해보세요.
import yfinance as yf

ticker = "005930.KS"
samsung = yf.Ticker(ticker)
start_date = "2024-01-01"
data = samsung.history(start=start_date)
data

# 1) 각 열 단위로 최대값을 출력하시오.
max_val = data.loc[:, 'Open':'Stock Splits'].max() # 모든 행에대한 열단위 최댓값
df1 = pd.DataFrame(max_val, columns=['max_value']) # 시리즈를 프레임으로

max_val_label = data.loc[:, 'Open':'Stock Splits'].idxmax() # 모든 행에대한 열단위 최댓값의 인덱스 라벨(날짜)
df1['date'] = max_val_label # 새로운 열 축을 생성하고 인덱스 라벨 적용
df1

# # 2) 각 열 단위로 최소값을 출력하시오.
min_val = data.loc[:, 'Open':'Stock Splits'].min()
df2 = pd.DataFrame(min_val, columns=['min_value'])

min_val_label = data.loc[:, 'Open':'Stock Splits'].idxmin()
df2['date'] = min_val_label
df2

# # 3) 각 열 단위로 최대값-최소값을 출력하시오.
df3 = pd.DataFrame(df1.max_value - df2.min_value, columns=['max - min'])
df3

# # 4) 기술통계를 구하시오.
data.describe()
df3.describe()

          max - min
count  7.000000e+00
mean   7.827007e+06
std    2.068375e+07
min    0.000000e+00
25%    6.800000e+03
50%    1.380000e+04
75%    1.415000e+04
max    5.473335e+07